"""
This is a setup.py script generated by py2applet

Usage:
    rm -r build dist
    python2.7 setup.py py2app -A
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'iconfile':'images/logo.icns',}

setup(
    app=APP,
    name = 'DocNetStat',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
